---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ingress_kustomization.yaml
  - network_policy.yaml
  - kustomize/frontend.yaml
  - kustomize/secrets.yaml
  - frontend/deployment.yaml
  - frontend/ingress.yaml
  - frontend/service.yaml
