---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1pwdsecrets-redirect
  namespace: redirect-namespace
spec:
  interval: 10m
  path: "cluster/redirect/certificates/secrets"
  dependsOn:
    - name: 1password-connect
      namespace: 1pwd
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-cluster
    namespace: flux-system
