---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: queenbee-frontend-ingress
  namespace: queenbee
  annotations:
    # a comment
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Content-Security-Policy "default-src 'self' https://api.mazemap.com; img-src 'self' blob: data:;style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://api.mazemap.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.mazemap.com https://www.google-analytics.com; font-src https://fonts.googleapis.com https://fonts.gstatic.com; connect-src 'self' https://queenbee-api-dev.login.no";
spec:
  ingressClassName: nginx-ntnu
  tls:
    - hosts:
        - queenbee-dev.login.no
  rules:
    - host: queenbee-dev.login.no
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: queenbee-frontend-svc
                port:
                  number: 4200
