---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beeformed
    part-of: beehive
    project: beeformed
    confidentiality: not-defined
    compliance: not-defined
  name: beeformed
  namespace: beeformed
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: beeformed
  template:
    metadata:
      labels:
        app: beeformed
        component: beeformed
        part-of: beehive
        project: beeformed
        confidentiality: not-defined
        compliance: not-defined
    spec:
      imagePullSecrets:
        - name: gitlab-deploy-key-beeformed
      containers:
        - name: webserver
          image: registry.login.no/tekkom/dev/beeformed:1.0.0-dev
          imagePullPolicy: IfNotPresent
          env:
            - name: AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: beeformed-secrets
                  key: AUTH_CLIENT_ID
            - name: AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: beeformed-secrets
                  key: AUTH_CLIENT_SECRET
            - name: AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: beeformed-secrets
                  key: AUTH_URL
            - name: NEXT_PUBLIC_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: beeformed-secrets
                  key: NEXT_PUBLIC_BASE_URL
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: beeformed-secrets
                  key: API_URL
          ports:
            - containerPort: 3000
              name: 3000tcp
              protocol: TCP
          resources:
            requests:
              memory: 128Mi
              cpu: 125m
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nginx
              topologyKey: kubernetes.io/hostname
