---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - secret_kustomization.yaml
  - db_kust.yaml
  - deployment.yaml
  - svc.yaml
  - ingress.yaml
  - pdb.yaml
  - np.yaml
