---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-policy.yaml
  - limitrange.yaml
  - resourcequota.yaml
  - kustomize/frontend.yaml
  - kustomize/secrets.yaml
  - kustomize/api.yaml
